version: "3.8"

services:
  autism-app:
    container_name: autism-app
    image: autism-app
    restart: always
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 12000:3000
