services:
  autism-app:
    container_name: autism-app
    image: autism-app:latest
    restart: unless-stopped
    build:
      context: .
    ports:
      - "12000:3000"
    environment:
      - NODE_ENV=production 
      - PORT=3000

